appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: VE3ce2HebkJElJuMKBmul3IVNdhrJjWsUA7Rpv1bXDzAXBfKxEAoTWv5tZLBgbZMXJuEP1T31NAzScHsO7aDSUmfuSY5RezGmZF3UTtbtMqAF4r43hapll06KyJEhEoKNtG5tH6PY38xBE7X0C4kWq3/9HkeeR7cj3i6Nnx2L7vpaYZ7BUS7vvySSQVjqLJhniqucp47fYLgJGNgJdlff8fT5rRVbTuGh8L3th85IPW53CwHO5qkuVppYS/9KmFe2shAuj+sefFI4F3DC+cjla+Mhc1O+hsaaQC4AnjZlAiW461K+gr8o8tRuo9UlZmgkyhZdP3eCECTwLL5MFXZDUF76Iwf1hWiUE+4F72P2tUgmUWHNvqlkcpWRHmoEoHO3OirNhsHq56+WhWTBHEpFrKe+j9d771VrtxnHQH/0lOTCFh+RoCOdB+i92WNyeUpNglhdL03El4Q5DhKNusIvYUxikdyNhllVwJuCyP9zsufJ037E1+Xu1/XSQr1ifidhfrnVh4wWupaVfSBs5Y4/v2EdqmarkdFWsbF+2T+IdBrzA2dEJMsV72d17n9XiEJv2kEsALtylaP1cnlUnEIMBk2Dd73d2Uu0czIxIVESs/zJ/2/+GA2s1PXHqQZ6lbBIgsjebdoBeEi/SJW2auA+URWIx05k4zWnd6vwkOt8J4=}
